<a href="https://colab.research.google.com/github/limyien-2025/data-science-toolkit/blob/main/Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

array_2x2 = np.array([[1, 2], [3, 4]])
print("2x2 array:\n", array_2x2)

2x2 array:
 [[1 2]
 [3 4]]


In [4]:
random_3x4 = np.random.rand(3, 4)
print("Random 3x4 array:\n", random_3x4)

Random 3x4 array:
 [[0.24934085 0.49221673 0.01178803 0.80956366]
 [0.98797746 0.4325974  0.06043009 0.90855465]
 [0.84899143 0.55585711 0.50829377 0.06751224]]


In [5]:
ones_array = np.ones((2, 3))
zeros_array = np.zeros((2, 3))

print("Array of ones:\n", ones_array)
print("Array of zeroes:\n", zeros_array)

Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array of zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
random_6x3 = np.random.rand(6, 3)
transposed_array = np.transpose(random_6x3)

print("Original 6x3 array:\n", random_6x3)
print("\nTransposed array (3x6):\n", transposed_array)

Original 6x3 array:
 [[0.81141078 0.14900622 0.99246123]
 [0.24115387 0.99807295 0.59330555]
 [0.28470244 0.02800445 0.99491546]
 [0.88804772 0.15162612 0.50942789]
 [0.09033212 0.03038455 0.6950883 ]
 [0.78358409 0.26446082 0.66253266]]

Transposed array (3x6):
 [[0.81141078 0.24115387 0.28470244 0.88804772 0.09033212 0.78358409]
 [0.14900622 0.99807295 0.02800445 0.15162612 0.03038455 0.26446082]
 [0.99246123 0.59330555 0.99491546 0.50942789 0.6950883  0.66253266]]


In [8]:
n, p, m = 2, 3, 4
A = np.random.rand(n, p)
B = np.random.rand(p, m)

dot_product = np.dot(A, B)

print("Matrix A (n x p):\n", A)
print("\nMatrix B (p x m):\n", B)
print("\nDot product (n x m):\n", dot_product)

Matrix A (n x p):
 [[0.23695972 0.29430993 0.46632174]
 [0.55617709 0.05631164 0.77058767]]

Matrix B (p x m):
 [[0.52227319 0.9982424  0.12311511 0.16936631]
 [0.2602915  0.8389969  0.86529119 0.89016242]
 [0.70115185 0.02564837 0.89219639 0.16157567]]

Dot product (n x m):
 [[0.52732643 0.49542875 0.69988768 0.37746288]
 [0.84543279 0.62220915 0.80471529 0.26883238]]
